
project 'AsyncDisplayKitDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AsyncDisplayKitDemo' do


pod 'SDWebImage'

pod 'AsyncDisplayKit'


end
